# Generated by Django 4.1.5 on 2023-07-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_category_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='Bids',
            new_name='LargestBid',
        ),
    ]
