# Generated by Django 4.1.5 on 2023-07-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.comment'),
        ),
    ]
