# Generated by Django 4.1.5 on 2023-07-28 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='DateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='ImageURL',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='ItemDescription',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='ItemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='LargestBid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Auctions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Bids',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='largest_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlisting'),
        ),
    ]
