# Generated by Django 4.1.5 on 2023-07-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_largest_bid_bid_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='No Category Listed', max_length=50),
        ),
    ]
