# Generated by Django 4.1.5 on 2023-08-01 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auctionlisting_potentialbuyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='potentialBuyers',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
