# Generated by Django 4.1.5 on 2023-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionlisting_potentialbuyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='openListing',
            field=models.BooleanField(default=True),
        ),
    ]
